### ISSUE TITLE
Suggestion: Report feature

### ISSUE THREAD

**Issue by Codeshark-NET** [ecosyste-ms/ost#104]
Howdy 🤠

As a user, if something is wrong with a project/repository, I would like to report that, adding a reason and an optional message. 

This should help us in identifying potential issues or hiccups on the list. 
This should be exposed via an endpoint.

^ Just a suggestion, adding it here for discussion

**Comment by andrew** [comment]
what kind of things wrong are you talking about? Do you have an example? This service is currently read-only, there's no authentication or spam detection, opening up an endpoint to let anyone write to the db isn't ideal.

**Comment by andrew** [comment]
Perhaps instead we could ask them to open an issue on this repo or the climatetriage repo instead?

**Comment by Codeshark-NET** [comment]
Yes that could be a pop-up suggesting that, on the frontend 🤔 

Either way I'll close down this again as this doesn't fit the responsibility of the API anyway 👍
