### ISSUE TITLE
Ignore bot activity in issue/pull request checks

### ISSUE THREAD

**Issue by andrew** [ecosyste-ms/ost#11]
> One important feedback on the review function. It looks like that pull request created by bots is also considered activity.

cc @Ly0n

**Comment by Ly0n** [comment]
The question is: Is there a unique way to distinguish a bot from a user on GitHub? I did a little research. And found this: https://stackoverflow.com/questions/52731464/can-we-use-github-api-to-determine-if-a-github-user-is-a-bot#:~:text=When%20querying%20https%3A%2F%2Fapi,type%20equals%20the%20string%20Bot%20.

**Comment by Ly0n** [comment]
I just compared this solution with the bots you found for the list of top commiters within OST. It work for some bots but not all of them. Here some example it does not work:
https://api.github.com/users/gitter-badger
https://api.github.com/users/JuliaTagBot
https://api.github.com/users/codacy-badger
https://api.github.com/users/actions-user

When the user name has a [bot] at the end it is also all the time a bot based on the type value. Here one example:
https://api.github.com/users/repo-mountie[bot]

For a first start it should be enough to filter the bot, which are labled as bots via "type". These bots also generate the most commits based on the user analysis we did for OST. For the remaining bots, we would have to keep a blacklist, which we can fill relatively easily with the most prominent cases.

**Comment by andrew** [comment]
bot percentages in the commits service: 2.5% of commits across all time, 9% of commits in the past year

**Comment by andrew** [comment]
Commit data up to date now, just need to sync it into the ost app and update

**Comment by Ly0n** [comment]
Thank you, Andrew. I will test this new feature later. The Bot Activity Detection feature will also be crucial for the next report, as it will allow us to filter projects that are only maintained by bot activity.
