### ISSUE TITLE
Implementing categories for issues and projects

### ISSUE THREAD

**Issue by Codeshark-NET** [ecosyste-ms/ost#66]
- [high] As a developer, I'd like for the issues/projects data to include a "category" property, so that I can categorize/sort/filter on this in the client.

- [low] As a developer, I'd like for the issues/projects to be filterable by "category", using a query param like ?cat= or similar, so that I can request a full category directly.

- [low] As a developer, I'd like to be able to query the API for a list of all the categories available, not just the ones returned from issues/projects, so that I can use this to show empty categories & more.

**Comment by andrew** [comment]
Do we wanted nested categories, like in the [readme](https://github.com/protontypes/open-sustainable-technology/blob/main/README.md#contents) of opensustain or just the second level ones per project.. i.e. should [bslib](https://github.com/FZJ-IEK3-VSA/bslib) be `["Energy Storage","Battery"]` or just `Battery`? cc @Ly0n

**Comment by andrew** [comment]
Projects now have `category` and `sub_category` fields
