### ISSUE TITLE
Avoid returning null values for certain fields

### ISSUE THREAD

**Issue by Codeshark-NET** [ecosyste-ms/ost#80]
As we discussed briefly earlier, certain fields are returning null (sometimes). 

This goes for:
* "name" (see nsidc/earthaccess)
* "language" (see softwareunderground/awesome-open-geoscience, metno/emep-ctm)
* "category" (see nsidc/earthaccess)

If they could return "N/A" or some other static value when null (if that's supposed to happen) that'd be great.

**Comment by andrew** [comment]
I've fixed a bug in syncing from the readme, that should fix the name and category issue, some projects don't have a language, they are just text, not sure if N/A is the best alternative, any thoughts @ly0n?

**Comment by andrew** [comment]
@Codeshark-NET just reimported everything, there shouldn't be any projects with name or category that is null now

**Comment by Ly0n** [comment]
> I've fixed a bug in syncing from the readme, that should fix the name and category issue, some projects don't have a language, they are just text, not sure if N/A is the best alternative, any thoughts @Ly0n?

We could list them under "unknown"?
